### ISSUE TITLE
Teach bitcoind-ncurses about btcd's config format

### ISSUE THREAD

**Issue by PRabahy** [esotericnonsense/bitcoind-ncurses#10]
Right now, I can get btcd and bitcoind-ncurses working by creating 2 separate config files (one that btcd can parse and another that bitcoind-ncurses can parse). This works, but if I change 1 files, I have to remember to change the other to keep them in sync. It would be nice if bitcoind-ncurses could parse btcd's config file directly.

**Comment by esotericnonsense** [comment]
I don't use btcd, but if anyone else wants to take a stab at this, I'm happy to merge.
