### ISSUE TITLE
Teach bitcoind-ncurses about getnetworkinfo subversion property

### ISSUE THREAD

**Issue by PRabahy** [esotericnonsense/bitcoind-ncurses#11]
A new enhancement to getnetworkinfo was just committed. https://github.com/bitcoin/bitcoin/commit/58d4b232840ee52e67f73eda6c6bd3cc22355b37 Bitcoind-ncurses should be able to use that to provide more accurate information on the main screen.

**Comment by esotericnonsense** [comment]
This is in as of commit 9cc7282a. Tested on Core v0.12.0 and v0.12.1.
Screenshot attached.
![subversion in monitor mode](https://cloud.githubusercontent.com/assets/7999704/14937710/ce5923e8-0f07-11e6-87b1-420515309992.png)
