### ISSUE TITLE
Message: invalid configuration file or missing values

### ISSUE THREAD

**Issue by jimerickson** [esotericnonsense/bitcoind-ncurses#16]
i have bitcoind-ncurses on fedora 22 with bitcoin-0.10.2. getting the following:

[jim@nuc bitcoind-ncurses]$ python2 main.py                                                                                                                                   
bitcoind-ncurses encountered an error
Message: invalid configuration file or missing values

it worked fine yesterday with the same config file. what am i doing wrong? config file as follows:

rpcuser=bitcoinrpc
rpcpassword=somelongrandomstring
datadir=/home/jim/.bitcoin
conf=bitcoin.conf
wallet=wallet.dat
paytxfee=0.0001
connect=192.168.1.162

**Comment by jimerickson** [comment]
i would like to add that bitcoind functions fine with this config file. so does "bitcoin-cli getinfo".

**Comment by BitpopCoin** [comment]
Why do you have  conf=bitcoin.conf

**Comment by jimerickson** [comment]
sorry i shall remove it. you are right it is redundant. thank you.

**Comment by BitpopCoin** [comment]
server=1

**Comment by jimerickson** [comment]
found this in the debug log:

2015-06-27 17:53:58 ThreadRPCServer incorrect password attempt from
127.0.0.1

but the password is the one given by bitcoind. what could be the problem?

**Comment by BitpopCoin** [comment]
Illegal character?

**Comment by jimerickson** [comment]
not that i can see. it is alpha numeric exactly as generated by bitcoind.

**Comment by BitpopCoin** [comment]
Extra space?

**Comment by jimerickson** [comment]
nope checked that.

**Comment by jimerickson** [comment]
changed the password. am now getting:

[jim@nuc bitcoind-ncurses]$ python2 main.py


bitcoind-ncurses encountered an error
Message: failed to connect to bitcoind (getinfo failed)

there is failed password attempt in the debug log.

**Comment by mitzip** [comment]
same here with "getinfo failed"

**Comment by esotericnonsense** [comment]
The RPC password issue is a bit of a mystery to me - best guess I have is that it wasn't being parsed correctly.

WRT 'getinfo failed' - that's just a hacky way of me determining that the client is up and responding to requests properly. In the future there should be a better heuristic and I think that the error message isn't very helpful.

Closing as you seem to have figured it out.
