### ISSUE TITLE
0.12 broke it?

### ISSUE THREAD

**Issue by BitpopCoin** [esotericnonsense/bitcoind-ncurses#20]
Please help. This program is all I use

**Comment by BitpopCoin** [comment]
Fixed!! https://github.com/achow101/bitcoind-ncurses/commit/5207a5d7e844ad84b3c4890012760a1ed4fd825e

**Comment by esotericnonsense** [comment]
Merged: a32a6d6e4c

Thanks achow101 for the fix and and bitpop for bringing this to my attention.
