### ISSUE TITLE
Crash if wallet disabled

### ISSUE THREAD

**Issue by nshopik** [esotericnonsense/bitcoind-ncurses#22]
New dev version seems won't start and go into traceback if wallet is disabled with error
`JSONRPCException: -32601: Method not found (disabled)`

Same goes if you try to connect to early and will tracebacks with
`bitcoinrpc.authproxy.JSONRPCException: -28: Loading block index...`
and later
`bitcoinrpc.authproxy.JSONRPCException: -28: Verifying blocks...`
This probably could be improved later on, to show these messages on splash screen.

**Comment by BitpopCoin** [comment]
I'm getting

Traceback (most recent call last):
File "bitcoind-ncurses/main.py", line 11, in
from gevent import monkey
ImportError: No module named gevent

**Comment by nshopik** [comment]
That's unrelated, you need `python-gevent` package installed if you are using debian

**Comment by BitpopCoin** [comment]
Is that new? Can i install it with pip?

**Comment by nshopik** [comment]
Yes that's new dependency according to code, i didn't tried with pip, but it should work `pip install gevent`

**Comment by BitpopCoin** [comment]
[ v0.1.0-dev ]Traceback (most recent call last):
                                                                                                              File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
                                                                       result = self._run(*self.args, **self.kwargs)
                                                                                                                      File "/root/bitcoind-ncurses/rpc2.py", line 65, in run
                                                   resp = self._call(req)
                                                                           File "/root/bitcoind-ncurses/rpc2.py", line 42, in _call
          result = getattr(self._handle, req.method)(*req.params)
                                                                   File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 116, in __call__
                                      raise JSONRPCException(response['error'])
                                                                               JSONRPCException
                                                                                               <Greenlet at 0x7f14fcecba50: <bound method BitcoinRPCClient.run of <rpc2.BitcoinRPCClient object at 0x7f14fc60b0d0>>> failed with JSONRPCException

**Comment by nshopik** [comment]
You sure this all error message? Seems `JSONRPCException` miss text of exception, check my first message, do you have wallet disabled in bitcoin.conf? Enabling will solve issue.

**Comment by BitpopCoin** [comment]
This is all I get http://i.imgur.com/Vxv2mZU.png

Yes it's disabled. I can't try enabling because I'm pruning.

**Comment by nshopik** [comment]
You can have wallet enabled with pruning, using 0.12 and later version of bitcoind

**Comment by BitpopCoin** [comment]
I had to reindex, but yes it works with wallet enabled. Idk why my error message was cut off

**Comment by esotericnonsense** [comment]
Hello!

The development version is broken. It's nowhere near finished. Apologies for the hassle.

Check out tag 'v0.0.23' and use that.

Going forward I would expect master to be subject to breaking changes - I'll tag a new release when I think it's stable.

**Comment by esotericnonsense** [comment]
The latest version adds an obvious yellow bar that indicates the development version is subject to breakage (currently undergoing a major refactor).

Latest 'stable' version: https://github.com/esotericnonsense/bitcoind-ncurses/releases/tag/v0.0.23

Closing for now.

**Comment by esotericnonsense** [comment]
After a bit of a blitz the development version should be back to some sense of stability.

A few features are disabled for now, but nothing too major. Monitor mode works fine.

**Comment by BitpopCoin** [comment]
Perfect
