### ISSUE TITLE
Start in specific mode?

### ISSUE THREAD

**Issue by bthaler1** [esotericnonsense/bitcoind-ncurses#25]
Is it possible to start in a specific mode?  It starts in the "Monitor" mode but I'd like to start in a different mode. On a whim I tried a command line argument "--mode" but it didn't work.  I'm spawning the process into a remote terminal but for some reason keystrokes I send to the remote terminal are not processed by the script.

**Comment by esotericnonsense** [comment]
Commit 8928b00 implements this feature.

Add to the configuration file (alongside rpcuser, rpcpassword):
mode=forks

for example.

The development feature is not quite fully functional yet (a few features like get block by timestamp and 'verbose' transaction mode are not implemented) but it should be relatively stable now.

**Comment by bthaler1** [comment]
Thanks for the update.
Now I'm getting "ImportError: No module named rpc" from rpc2.py line 8

I tried changing a few things around to make it work but I don't know enough about Python coding to get very far.

**Comment by esotericnonsense** [comment]
Commit 426a86b fixes that error. My local copy differed from git slightly.

**Comment by bthaler1** [comment]
Now I'm getting this:
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    rpcuser=cfg["rpcuser"],
KeyError: 'rpcuser'

My bitcoin.conf has looks like this:
rpcuser=userxxx
rpcpassword=passwordxxx

I can connect to my bitcoind instance using bitcoin-cli and the same bitcoin.conf file so I'm fairly certain my conf file is OK.

**Comment by bthaler1** [comment]
You can disregard my last comment above.  It is working now, including the initial mode.  The problem above is because I wasn't specifying the absolute path to the config file, but rather used a tilde as a shortcut to my home directory.  I'm not sure why that didn't throw the IO error.

Anyway thanks for the changes.  Everything seems to be working really well now.

**Comment by esotericnonsense** [comment]
That's good to hear. I'm not sure either.
Thanks for reporting this. Please do report any issues that crop up with the new development version if it goes wrong.
