### ISSUE TITLE
ImportError: No module named gevent

### ISSUE THREAD

**Issue by rubru70** [esotericnonsense/bitcoind-ncurses#31]
~/Downloads/bitcoind-ncurses $ python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from gevent import monkey
ImportError: No module named gevent

**Comment by nshopik** [comment]
`pip install gevent`

**Comment by rubru70** [comment]
Thank you!

Is it possible to connect to another host (^=localhost,127.0.0.1)?

What config parameter in bitcoinconf ncurses dir needs to be adjust?

best regards

Rudolf
